apiVersion: apps/v1
kind: Deployment
metadata:
  name: testweb-app1
  labels:
    app: testweb-app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: testweb-app1
  template:
    metadata:
      labels:
        app: testweb-app1
    spec:
      containers:
        - name: container10
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}

