apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: testweb-app1
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 82
      targetPort: 3000
  selector:
    app: testweb-app1

