name: HelmChart Build and Deploy

on:
  push:
    branches:
      - main

env:
#   DOCKERHUB_USERNAME: anshuman01
#   DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
#   DOCKER_IMAGE_NAME: test-image
  HELM_CHART_PATH: ./testchart1
  RELEASE_NAME: mytest
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  AWS_ECR_REPOSITORY: my-ecr-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        run: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 774015705338.dkr.ecr.us-east-1.amazonaws.com
            docker build -t testbin .
        
      - name: Tag and push Docker image to AWS ECR
        run: |
          docker tag testbin:latest 774015705338.dkr.ecr.us-east-1.amazonaws.com/testbin:latest
          docker push 774015705338.dkr.ecr.us-east-1.amazonaws.com/testbin:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Helm chart
        run: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_CHART_PATH }}
