name: helmchart Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: anshuman01
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKER_IMAGE_NAME: anshuman01/test-image
  HELM_CHART_PATH: /home/anshuman/helm
  RELEASE_NAME: mytest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Helm chart
        run: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_CHART_PATH }}
