name: Build and Deploy

on:
  push:
    branches:
      - helm-01

env:
  DOCKERHUB_USERNAME: anshuman01
  DOCKER_IMAGE_NAME: test-image
  HELM_CHART_PATH: ./testchart1
  RELEASE_NAME: devops-helm
  EC2_HOST: 172-31-88-138
  EC2_USERNAME: ubuntu
  EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Helm chart
        run: |
          helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_CHART_PATH }}

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Helm chart on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" ${EC2_USERNAME}@${EC2_HOST} 'helm upgrade $RELEASE_NAME $HELM_CHART_PATH'
